name: delay_snake3
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - -40.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    bend180:
      function: bend_euler
      settings:
        angle: 180
    cross_section: strip
    length: 1600.0
    length0: 0.0
    length2: 0.0
    n: 2
  full:
    bend180:
      function: bend_euler
      settings:
        angle: 180
    cross_section: strip
    length: 1600.0
    length0: 0.0
    length2: 0.0
    n: 2
  function_name: delay_snake3
  info: {}
  info_version: 2
  module: gdsfactory.components.delay_snake3
  name: delay_snake3
