name: mzit_lattice
ports:
  o1:
    center:
    - -10.0
    - -0.6
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -10.0
    - 1.4
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - -6.0
    - 21.4
    layer:
    - 1
    - 0
    name: o3
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - -6.0
    - 23.4
    layer:
    - 1
    - 0
    name: o4
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    coupler_gaps:
    - 0.2
    - 0.3
    coupler_lengths:
    - 10.0
    - 20.0
    delta_lengths:
    - 10.0
    mzi:
      function: mzit
  full:
    coupler_gaps:
    - 0.2
    - 0.3
    coupler_lengths:
    - 10.0
    - 20.0
    delta_lengths:
    - 10.0
    mzi:
      function: mzit
  function_name: mzit_lattice
  info: {}
  info_version: 2
  module: gdsfactory.components.mzit_lattice
  name: mzit_lattice
