name: die
ports: {}
settings:
  changed: {}
  child: null
  default:
    bbox_layer: FLOORPLAN
    die_name: chip99
    draw_corners: false
    layer: FLOORPLAN
    size:
    - 10000.0
    - 10000.0
    street_length: 1000.0
    street_width: 100.0
    text:
      function: text
    text_location: SW
    text_size: 100.0
  full:
    bbox_layer: FLOORPLAN
    die_name: chip99
    draw_corners: false
    layer: FLOORPLAN
    size:
    - 10000.0
    - 10000.0
    street_length: 1000.0
    street_width: 100.0
    text:
      function: text
    text_location: SW
    text_size: 100.0
  function_name: die
  info: {}
  info_version: 2
  module: gdsfactory.components.die
  name: die
