name: aar_bundles
ports: {}
settings:
  changed: {}
  child: null
  default: {}
  full: {}
  function_name: aar_bundles
  info:
    instances:
    - wg_a10
    - wg_a20
    - wg_b10
    - wg_b20
    - wg_c10
    - wg_c20
    - wg_d10
    - wg_d20
    - wg_e10
    - wg_e20
    - wg_f10
    - wg_f20
    - wg_g10
    - wg_g20
    - wg_a11
    - wg_a21
    - wg_b11
    - wg_b21
    - wg_c11
    - wg_c21
    - wg_d11
    - wg_d21
    - wg_e11
    - wg_e21
    - wg_f11
    - wg_f21
    - wg_g11
    - wg_g21
    - wg_a12
    - wg_a22
    - wg_b12
    - wg_b22
    - wg_c12
    - wg_c22
    - wg_d12
    - wg_d22
    - wg_e12
    - wg_e22
    - wg_f12
    - wg_f22
    - wg_g12
    - wg_g22
    - wg_a13
    - wg_a23
    - wg_b13
    - wg_b23
    - wg_c13
    - wg_c23
    - wg_d13
    - wg_d23
    - wg_e13
    - wg_e23
    - wg_f13
    - wg_f23
    - wg_g13
    - wg_g23
    - wg_a14
    - wg_a24
    - wg_b14
    - wg_b24
    - wg_c14
    - wg_c24
    - wg_d14
    - wg_d24
    - wg_e14
    - wg_e24
    - wg_f14
    - wg_f24
    - wg_g14
    - wg_g24
  info_version: 2
  module: yaml_jinja
  name: aar_bundles
