name: fiber_array
ports:
  F0:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F0
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F1
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F2:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F2
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F3:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F3
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F4:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F4
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F5:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F5
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F6:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F6
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
  F7:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F7
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
settings:
  changed: {}
  child: null
  default:
    cladding_diameter: 125
    core_diameter: 10
    layer_cladding: WGCLAD
    layer_core: WG
    n: 8
    pitch: 127.0
  full:
    cladding_diameter: 125
    core_diameter: 10
    layer_cladding: WGCLAD
    layer_core: WG
    n: 8
    pitch: 127.0
  function_name: fiber_array
  info: {}
  info_version: 2
  module: gdsfactory.components.fiber_array
  name: fiber_array
