name: pad_array_orientation90
ports:
  e11:
    center:
    - 0.0
    - 0.0
    layer:
    - 49
    - 0
    name: e11
    orientation: 90
    port_type: electrical
    shear_angle: null
    width: 100.0
  e12:
    center:
    - 150.0
    - 0.0
    layer:
    - 49
    - 0
    name: e12
    orientation: 90
    port_type: electrical
    shear_angle: null
    width: 100.0
  e13:
    center:
    - 300.0
    - 0.0
    layer:
    - 49
    - 0
    name: e13
    orientation: 90
    port_type: electrical
    shear_angle: null
    width: 100.0
  e14:
    center:
    - 450.0
    - 0.0
    layer:
    - 49
    - 0
    name: e14
    orientation: 90
    port_type: electrical
    shear_angle: null
    width: 100.0
  e15:
    center:
    - 600.0
    - 0.0
    layer:
    - 49
    - 0
    name: e15
    orientation: 90
    port_type: electrical
    shear_angle: null
    width: 100.0
  e16:
    center:
    - 750.0
    - 0.0
    layer:
    - 49
    - 0
    name: e16
    orientation: 90
    port_type: electrical
    shear_angle: null
    width: 100.0
settings:
  changed:
    orientation: 90
  child: null
  default:
    columns: 6
    orientation: 270
    pad: pad
    rows: 1
    spacing:
    - 150.0
    - 150.0
  full:
    columns: 6
    orientation: 90
    pad: pad
    rows: 1
    spacing:
    - 150.0
    - 150.0
  function_name: pad_array
  info:
    size:
    - 100.0
    - 100.0
  info_version: 2
  module: gdsfactory.components.pad
  name: pad_array_orientation90
