name: ring_double
ports:
  o1:
    center:
    - -13.01
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - -13.01
    - 21.41
    layer:
    - 1
    - 0
    name: o3
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 13.0
    - 21.41
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    bend:
      function: bend_euler
    coupler_ring:
      function: coupler_ring
    cross_section: strip
    gap: 0.2
    length_x: 0.01
    length_y: 0.01
    radius: 10.0
  full:
    bend:
      function: bend_euler
    coupler_ring:
      function: coupler_ring
    cross_section: strip
    gap: 0.2
    length_x: 0.01
    length_y: 0.01
    radius: 10.0
  function_name: ring_double
  info: {}
  info_version: 2
  module: gdsfactory.components.ring_double
  name: ring_double
