name: greek_cross_with_pads
ports: {}
settings:
  changed: {}
  child: null
  default:
    greek_cross_component:
      function: greek_cross
    pad:
      function: pad
    pad_spacing: 150.0
    pad_via:
      function: via_stack
      settings:
        layers:
        - M1
        - M2
        - M3
        vias:
        - function: via
          settings:
            enclosure: 2
            layer: VIA1
        - function: via
          settings:
            layer: VIA2
        - null
    xs_metal:
      function: cross_section
      settings:
        gap: 5
        layer: M1
        min_length: 5
        port_names:
        - e1
        - e2
        port_types:
        - electrical
        - electrical
        radius: null
        width: 10.0
  full:
    greek_cross_component:
      function: greek_cross
    pad:
      function: pad
    pad_spacing: 150.0
    pad_via:
      function: via_stack
      settings:
        layers:
        - M1
        - M2
        - M3
        vias:
        - function: via
          settings:
            enclosure: 2
            layer: VIA1
        - function: via
          settings:
            layer: VIA2
        - null
    xs_metal:
      function: cross_section
      settings:
        gap: 5
        layer: M1
        min_length: 5
        port_names:
        - e1
        - e2
        port_types:
        - electrical
        - electrical
        radius: null
        width: 10.0
  function_name: greek_cross_with_pads
  info: {}
  info_version: 2
  module: gdsfactory.components.greek_cross
  name: greek_cross_with_pads
