name: mmi1x2_extend_ports
ports:
  o1:
    center:
    - -15.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 20.5
    - 0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 20.5
    - -0.625
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child:
    changed: {}
    child: null
    default:
      cross_section: strip
      gap_mmi: 0.25
      length_mmi: 5.5
      length_taper: 10.0
      straight:
        function: straight
      taper:
        function: taper
      width: null
      width_mmi: 2.5
      width_taper: 1.0
      with_bbox: true
    full:
      cross_section: strip
      gap_mmi: 0.25
      length_mmi: 5.5
      length_taper: 10.0
      straight:
        function: straight
      taper:
        function: taper
      width: null
      width_mmi: 2.5
      width_taper: 1.0
      with_bbox: true
    function_name: mmi1x2
    info: {}
    info_version: 2
    module: gdsfactory.components.mmi1x2
    name: mmi1x2
  default:
    centered: false
    component:
      function: mmi1x2
    cross_section: null
    extension: null
    extension_port_names: null
    length: 5.0
    port1: null
    port2: null
    port_names: null
    port_type: optical
  full:
    centered: false
    component:
      function: mmi1x2
    cross_section: null
    extension: null
    extension_port_names: null
    length: 5.0
    port1: null
    port2: null
    port_names: null
    port_type: optical
  function_name: extend_ports
  info: {}
  info_version: 2
  module: gdsfactory.components.extension
  name: mmi1x2_extend_ports
