name: grating_coupler_rectangular_arbitrary_slab
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt_te_1550_15:
    center:
    - 153.5
    - 0.0
    layer:
    - 1
    - 0
    name: opt_te_1550_15
    orientation: 0
    port_type: opt_te_1550_15
    shear_angle: null
    width: 11.0
settings:
  changed: {}
  child: null
  default:
    cross_section: strip
    fiber_angle: 15
    gaps:
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    layer_slab: SLAB150
    length_taper: 150.0
    polarization: te
    slab_offset: 2.0
    taper:
      function: taper_strip_to_ridge
      settings:
        layer_slab: SLAB150
    wavelength: 1.55
    width_grating: 11.0
    widths:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
  full:
    cross_section: strip
    fiber_angle: 15
    gaps:
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    layer_slab: SLAB150
    length_taper: 150.0
    polarization: te
    slab_offset: 2.0
    taper:
      function: taper_strip_to_ridge
      settings:
        layer_slab: SLAB150
    wavelength: 1.55
    width_grating: 11.0
    widths:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
  function_name: grating_coupler_rectangular_arbitrary_slab
  info:
    polarization: te
    wavelength: 1.55
  info_version: 2
  module: gdsfactory.components.grating_coupler_rectangular_arbitrary_slab
  name: grating_coupler_rectangular_arbitrary_slab
