name: aar_slalom
ports: {}
settings:
  changed: {}
  child: null
  default: {}
  full: {}
  function_name: aar_slalom
  info:
    instances:
    - wg_d1
    - wg_d2
  info_version: 2
  module: yaml_jinja
  name: aar_slalom
