name: straight_d6abaab6_extend_ports_5819b9cb
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 20.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
              settings:
                function:
                  function: add_pin_rectangle_inside
                  settings:
                    layer_label: null
                    pin_length: 0.001
            bbox_layers:
            - SLAB90
            bbox_offsets:
            - 3
            info:
              type: rib
            name: strip
            radius: 20
    extension:
      function: taper_strip_to_ridge
    port1: o2
    port2: o1
  child:
    changed:
      cross_section:
        function: cross_section
        settings:
          add_bbox: null
          add_pins:
            function: add_pins
            settings:
              function:
                function: add_pin_rectangle_inside
                settings:
                  layer_label: null
                  pin_length: 0.001
          bbox_layers:
          - SLAB90
          bbox_offsets:
          - 3
          info:
            type: rib
          name: strip
          radius: 20
    child: null
    default:
      cross_section: strip
      length: 10.0
      npoints: 2
      with_bbox: true
    full:
      cross_section:
        function: cross_section
        settings:
          add_bbox: null
          add_pins:
            function: add_pins
            settings:
              function:
                function: add_pin_rectangle_inside
                settings:
                  layer_label: null
                  pin_length: 0.001
          bbox_layers:
          - SLAB90
          bbox_offsets:
          - 3
          info:
            type: rib
          name: strip
          radius: 20
      length: 10.0
      npoints: 2
      with_bbox: true
    function_name: straight
    info:
      cross_section:
        function: cross_section
        settings:
          add_bbox: null
          add_pins:
            function: add_pins
            settings:
              function:
                function: add_pin_rectangle_inside
                settings:
                  layer_label: null
                  pin_length: 0.001
          bbox_layers:
          - SLAB90
          bbox_offsets:
          - 3
          info:
            type: rib
          name: strip
          radius: 20
      function_name: cross_section
      length: 10.0
      route_info:
        length: 10.0
        rib_length: 10.0
        type: rib
        weight: 10.0
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        auto_widen: false
        auto_widen_minimum_length: 200.0
        bbox_layers:
        - SLAB90
        bbox_offsets:
        - 3
        cladding_layers: null
        cladding_offsets: null
        cladding_simplify: null
        decorator: null
        end_straight_length: 0.01
        gap: 3.0
        info:
          type: rib
        layer: WG
        min_length: 0.01
        mirror: false
        name: strip
        offset: 0
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        radius: 20
        sections: null
        snap_to_grid: null
        start_straight_length: 0.01
        taper_length: 10.0
        width: 0.5
        width_wide: null
      type: rib
      width: 0.5
    info_version: 2
    module: gdsfactory.components.straight
    name: straight_d6abaab6
  default:
    centered: false
    component:
      function: mmi1x2
    cross_section: null
    extension: null
    extension_port_names: null
    length: 5.0
    port1: null
    port2: null
    port_names: null
    port_type: optical
  full:
    centered: false
    component:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
              settings:
                function:
                  function: add_pin_rectangle_inside
                  settings:
                    layer_label: null
                    pin_length: 0.001
            bbox_layers:
            - SLAB90
            bbox_offsets:
            - 3
            info:
              type: rib
            name: strip
            radius: 20
    cross_section: null
    extension:
      function: taper_strip_to_ridge
    extension_port_names: null
    length: 5.0
    port1: o2
    port2: o1
    port_names: null
    port_type: optical
  function_name: extend_ports
  info:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        bbox_layers:
        - SLAB90
        bbox_offsets:
        - 3
        info:
          type: rib
        name: strip
        radius: 20
    function_name: cross_section
    length: 10.0
    route_info:
      length: 10.0
      rib_length: 10.0
      type: rib
      weight: 10.0
    settings:
      add_bbox: null
      add_pins:
        function: add_pins
        settings:
          function:
            function: add_pin_rectangle_inside
            settings:
              layer_label: null
              pin_length: 0.001
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - SLAB90
      bbox_offsets:
      - 3
      cladding_layers: null
      cladding_offsets: null
      cladding_simplify: null
      decorator: null
      end_straight_length: 0.01
      gap: 3.0
      info:
        type: rib
      layer: WG
      min_length: 0.01
      mirror: false
      name: strip
      offset: 0
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      radius: 20
      sections: null
      snap_to_grid: null
      start_straight_length: 0.01
      taper_length: 10.0
      width: 0.5
      width_wide: null
    type: rib
    width: 0.5
  info_version: 2
  module: gdsfactory.components.extension
  name: straight_d6abaab6_extend_ports_5819b9cb
