name: array_with_fanout_2d
ports:
  o1_1_1:
    center:
    - -45.0
    - -80.0
    layer:
    - 1
    - 0
    name: o1_1_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o1_2_1:
    center:
    - -45.0
    - 70.0
    layer:
    - 1
    - 0
    name: o1_2_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_1_1:
    center:
    - -45.0
    - -70.0
    layer:
    - 1
    - 0
    name: o2_1_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_2_1:
    center:
    - -45.0
    - 80.0
    layer:
    - 1
    - 0
    name: o2_2_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3_1_1:
    center:
    - -45.0
    - -60.0
    layer:
    - 1
    - 0
    name: o3_1_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3_2_1:
    center:
    - -45.0
    - 90.0
    layer:
    - 1
    - 0
    name: o3_2_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    columns: 3
    pitch: 150.0
    pitch_x: null
    pitch_y: null
    rows: 2
  full:
    columns: 3
    pitch: 150.0
    pitch_x: null
    pitch_y: null
    rows: 2
  function_name: array_with_fanout_2d
  info: {}
  info_version: 2
  module: gdsfactory.components.array_with_fanout
  name: array_with_fanout_2d
