name: straight_heater_meander_doped
ports:
  l_e1:
    center:
    - 0.0
    - 2.0
    layer:
    - 45
    - 0
    name: l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  l_e2:
    center:
    - 0.75
    - 2.75
    layer:
    - 45
    - 0
    name: l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  l_e3:
    center:
    - 1.5
    - 2.0
    layer:
    - 45
    - 0
    name: l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  l_e4:
    center:
    - 0.75
    - 1.25
    layer:
    - 45
    - 0
    name: l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  o1:
    center:
    - -25.0
    - -0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 74.778
    - 6.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e1:
    center:
    - 68.28
    - 2.0
    layer:
    - 45
    - 0
    name: r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  r_e2:
    center:
    - 69.03
    - 2.75
    layer:
    - 45
    - 0
    name: r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  r_e3:
    center:
    - 69.78
    - 2.0
    layer:
    - 45
    - 0
    name: r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 1.5
  r_e4:
    center:
    - 69.03
    - 1.25
    layer:
    - 45
    - 0
    name: r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 1.5
settings:
  changed: {}
  child: null
  default:
    cross_section: strip
    extension_length: 15.0
    heater_width: 1.5
    layers_doping:
    - P
    - PP
    - PPP
    length: 300.0
    port_orientation1: null
    port_orientation2: null
    radius: 5.0
    spacing: 2.0
    straight_widths:
    - 0.8
    - 0.9
    - 0.8
    taper_length: 10
    via_stack:
      function: via_stack
      settings:
        layers:
        - M1
        - M2
        size:
        - 1.5
        - 1.5
        vias:
        - function: via
          settings:
            enclosure: 0.1
            layer: VIAC
            size:
            - 0.1
            - 0.1
            spacing:
            - 0.2
            - 0.2
        - function: via
          settings:
            enclosure: 0.1
            layer: VIA1
            size:
            - 0.1
            - 0.1
            spacing:
            - 0.2
            - 0.2
  full:
    cross_section: strip
    extension_length: 15.0
    heater_width: 1.5
    layers_doping:
    - P
    - PP
    - PPP
    length: 300.0
    port_orientation1: null
    port_orientation2: null
    radius: 5.0
    spacing: 2.0
    straight_widths:
    - 0.8
    - 0.9
    - 0.8
    taper_length: 10
    via_stack:
      function: via_stack
      settings:
        layers:
        - M1
        - M2
        size:
        - 1.5
        - 1.5
        vias:
        - function: via
          settings:
            enclosure: 0.1
            layer: VIAC
            size:
            - 0.1
            - 0.1
            spacing:
            - 0.2
            - 0.2
        - function: via
          settings:
            enclosure: 0.1
            layer: VIA1
            size:
            - 0.1
            - 0.1
            spacing:
            - 0.2
            - 0.2
  function_name: straight_heater_meander_doped
  info: {}
  info_version: 2
  module: gdsfactory.components.straight_heater_meander_doped
  name: straight_heater_meander_doped
