name: coupler_full
ports:
  o1:
    center:
    - -10.0
    - -2.5
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.4
  o2:
    center:
    - -10.0
    - 2.5
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.6
  o3:
    center:
    - 50.0
    - 2.5
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.4
  o4:
    center:
    - 50.0
    - -2.5
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.6
settings:
  changed: {}
  child: null
  default:
    coupling_length: 40.0
    cross_section: strip
    dw: 0.1
    dx: 10.0
    dy: 5.0
    gap: 0.5
  full:
    coupling_length: 40.0
    cross_section: strip
    dw: 0.1
    dx: 10.0
    dy: 5.0
    gap: 0.5
  function_name: coupler_full
  info:
    function_name: cross_section
    settings:
      add_bbox: null
      add_pins:
        function: add_pins
        settings:
          function:
            function: add_pin_rectangle_inside
            settings:
              layer_label: null
              pin_length: 0.001
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers: null
      bbox_offsets: null
      cladding_layers: null
      cladding_offsets: null
      cladding_simplify: null
      decorator: null
      end_straight_length: 0.01
      gap: 3.0
      info:
        type: strip
      layer: WG
      min_length: 0.01
      mirror: false
      name: strip
      offset: 0
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      radius: 10.0
      sections: null
      snap_to_grid: null
      start_straight_length: 0.01
      taper_length: 10.0
      width: 0.5
      width_wide: null
    type: strip
  info_version: 2
  module: gdsfactory.components.coupler_full
  name: coupler_full
