name: straight_add_grating_couplers
ports: {}
settings:
  changed: {}
  child:
    changed: {}
    child: null
    default:
      cross_section: strip
      length: 10.0
      npoints: 2
      with_bbox: true
    full:
      cross_section: strip
      length: 10.0
      npoints: 2
      with_bbox: true
    function_name: straight
    info:
      cross_section: strip
      function_name: cross_section
      length: 10.0
      route_info:
        length: 10.0
        strip_length: 10.0
        type: strip
        weight: 10.0
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        auto_widen: false
        auto_widen_minimum_length: 200.0
        bbox_layers: null
        bbox_offsets: null
        cladding_layers: null
        cladding_offsets: null
        cladding_simplify: null
        decorator: null
        end_straight_length: 0.01
        gap: 3.0
        info:
          type: strip
        layer: WG
        min_length: 0.01
        mirror: false
        name: strip
        offset: 0
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        radius: 10.0
        sections: null
        snap_to_grid: null
        start_straight_length: 0.01
        taper_length: 10.0
        width: 0.5
        width_wide: null
      type: strip
      width: 0.5
    info_version: 2
    module: gdsfactory.components.straight
    name: straight
  default:
    component:
      function: straight
    component_name: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label:
    - 200
    - 0
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  full:
    component:
      function: straight
    component_name: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label:
    - 200
    - 0
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  function_name: add_grating_couplers
  info:
    cross_section: strip
    function_name: cross_section
    length: 10.0
    polarization: te
    route_info:
      length: 10.0
      strip_length: 10.0
      type: strip
      weight: 10.0
    settings:
      add_bbox: null
      add_pins:
        function: add_pins
        settings:
          function:
            function: add_pin_rectangle_inside
            settings:
              layer_label: null
              pin_length: 0.001
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers: null
      bbox_offsets: null
      cladding_layers: null
      cladding_offsets: null
      cladding_simplify: null
      decorator: null
      end_straight_length: 0.01
      gap: 3.0
      info:
        type: strip
      layer: WG
      min_length: 0.01
      mirror: false
      name: strip
      offset: 0
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      radius: 10.0
      sections: null
      snap_to_grid: null
      start_straight_length: 0.01
      taper_length: 10.0
      width: 0.5
      width_wide: null
    type: strip
    wavelength: 1.53
    width: 0.5
  info_version: 2
  module: gdsfactory.components.add_grating_couplers
  name: straight_add_grating_couplers
