name: grating_coupler_elliptical_arbitrary
ports:
  o1:
    center:
    - 0.25
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
  opt_te_1554_15:
    center:
    - 19.475
    - 0.0
    layer:
    - 1
    - 0
    name: opt_te_1554_15
    orientation: 0
    port_type: opt_te_1554_15
    shear_angle: null
    width: 10
settings:
  changed: {}
  child: null
  default:
    bias_gap: 0
    cross_section: strip
    fiber_angle: 15.0
    gaps:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    layer_grating: null
    layer_slab: SLAB150
    nclad: 1.443
    polarization: te
    spiked: true
    taper_angle: 60.0
    taper_length: 16.6
    taper_to_slab_offset: -3.0
    wavelength: 1.554
    widths:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
  full:
    bias_gap: 0
    cross_section: strip
    fiber_angle: 15.0
    gaps:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    layer_grating: null
    layer_slab: SLAB150
    nclad: 1.443
    polarization: te
    spiked: true
    taper_angle: 60.0
    taper_length: 16.6
    taper_to_slab_offset: -3.0
    wavelength: 1.554
    widths:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
  function_name: grating_coupler_elliptical_arbitrary
  info:
    polarization: te
    wavelength: 1.554
  info_version: 2
  module: gdsfactory.components.grating_coupler_elliptical_arbitrary
  name: grating_coupler_elliptical_arbitrary
