name: grating_coupler_rectangular
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt_te_1550_15:
    center:
    - 157.219
    - 0.0
    layer:
    - 1
    - 0
    name: opt_te_1550_15
    orientation: 0
    port_type: opt_te_1550_15
    shear_angle: null
    width: 11.0
settings:
  changed: {}
  child: null
  default:
    cross_section: strip
    fiber_angle: 15
    fill_factor: 0.5
    layer_slab: SLAB150
    length_taper: 150.0
    n_periods: 20
    period: 0.75
    polarization: te
    slab_offset: 1.0
    slab_xmin: -1.0
    taper:
      function: taper
    wavelength: 1.55
    width_grating: 11.0
  full:
    cross_section: strip
    fiber_angle: 15
    fill_factor: 0.5
    layer_slab: SLAB150
    length_taper: 150.0
    n_periods: 20
    period: 0.75
    polarization: te
    slab_offset: 1.0
    slab_xmin: -1.0
    taper:
      function: taper
    wavelength: 1.55
    width_grating: 11.0
  function_name: grating_coupler_rectangular
  info:
    polarization: te
    wavelength: 1.55
  info_version: 2
  module: gdsfactory.components.grating_coupler_rectangular
  name: grating_coupler_rectangular
