name: aar_start_end_customizations
ports: {}
settings:
  changed: {}
  child: null
  default: {}
  full: {}
  function_name: aar_start_end_customizations
  info:
    instances:
    - wg_a1
    - wg_a2
    - wg_b1
    - wg_b2
    - wg_c1
    - wg_c2
    - wg_d1
    - wg_d2
    - wg_e1
    - wg_e2
    - wg_f1
    - wg_f2
  info_version: 2
  module: yaml_jinja
  name: aar_start_end_customizations
