name: rectangle_11b0bf80
ports:
  e1:
    center:
    - -5.2
    - 0.0
    layer:
    - 204
    - 0
    name: e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.4
  e2:
    center:
    - 0.0
    - 5.2
    layer:
    - 204
    - 0
    name: e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 10.4
  e3:
    center:
    - 5.2
    - 0.0
    layer:
    - 204
    - 0
    name: e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.4
  e4:
    center:
    - 0.0
    - -5.2
    layer:
    - 204
    - 0
    name: e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 10.4
settings:
  changed:
    centered: true
    layer: TM
    size:
    - 10.4
    - 10.4
  child: null
  default:
    centered: false
    layer: WG
    port_orientations:
    - 180
    - 90
    - 0
    - -90
    port_type: electrical
    size:
    - 4.0
    - 2.0
  full:
    centered: true
    layer: TM
    port_orientations:
    - 180
    - 90
    - 0
    - -90
    port_type: electrical
    size:
    - 10.4
    - 10.4
  function_name: rectangle
  info: {}
  info_version: 2
  module: gdsfactory.components.rectangle
  name: rectangle_11b0bf80
