name: straight_heater_meander
ports:
  l_e1:
    center:
    - -21.0
    - 2.0
    layer:
    - 49
    - 0
    name: l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e2:
    center:
    - -15.5
    - 7.5
    layer:
    - 49
    - 0
    name: l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e3:
    center:
    - -10.0
    - 2.0
    layer:
    - 49
    - 0
    name: l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e4:
    center:
    - -15.5
    - -3.5
    layer:
    - 49
    - 0
    name: l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  o1:
    center:
    - -25.0
    - -0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 74.778
    - 4.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e1:
    center:
    - 79.778
    - 2.0
    layer:
    - 49
    - 0
    name: r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e2:
    center:
    - 85.278
    - 7.5
    layer:
    - 49
    - 0
    name: r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e3:
    center:
    - 90.778
    - 2.0
    layer:
    - 49
    - 0
    name: r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e4:
    center:
    - 85.278
    - -3.5
    layer:
    - 49
    - 0
    name: r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  changed: {}
  child: null
  default:
    cross_section: strip
    extension_length: 15.0
    heater_taper_length: 10.0
    heater_width: 2.5
    layer_heater: HEATER
    length: 300.0
    port_orientation1: null
    port_orientation2: null
    radius: 5.0
    spacing: 2.0
    straight_widths:
    - 0.8
    - 0.9
    - 0.8
    taper_length: 10
    via_stack: via_stack_heater_mtop
  full:
    cross_section: strip
    extension_length: 15.0
    heater_taper_length: 10.0
    heater_width: 2.5
    layer_heater: HEATER
    length: 300.0
    port_orientation1: null
    port_orientation2: null
    radius: 5.0
    spacing: 2.0
    straight_widths:
    - 0.8
    - 0.9
    - 0.8
    taper_length: 10
    via_stack: via_stack_heater_mtop
  function_name: straight_heater_meander
  info: {}
  info_version: 2
  module: gdsfactory.components.straight_heater_meander
  name: straight_heater_meander
