name: ring_single_bend_coupler
ports:
  o1:
    center:
    - -16.0
    - 15.7
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 16.0
    - 15.7
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    bend:
      function: bend_circular
    coupling_angle_coverage: 180.0
    cross_section_inner: strip
    cross_section_outer: strip
    gap: 0.2
    length_x: 0.6
    length_y: 0.6
    radius: 5.0
  full:
    bend:
      function: bend_circular
    coupling_angle_coverage: 180.0
    cross_section_inner: strip
    cross_section_outer: strip
    gap: 0.2
    length_x: 0.6
    length_y: 0.6
    radius: 5.0
  function_name: ring_single_bend_coupler
  info: {}
  info_version: 2
  module: gdsfactory.components.ring_single_bend_coupler
  name: ring_single_bend_coupler
