name: C$3
ports:
  o1:
    center:
    - 10.0
    - 20.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 1.0
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 1.0
settings:
  changed: {}
  child: null
  default:
    layer: WG
    size:
    - 10.0
    - 20.0
    width: 1.0
  full:
    layer: WG
    size:
    - 10.0
    - 20.0
    width: 1.0
  function_name: C
  info: {}
  info_version: 2
  module: gdsfactory.components.C
  name: C
