name: mmi1x2_splitter_chain
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 15.5
    - -0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 52.0
    - 2.0
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 88.5
    - 4.625
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o5:
    center:
    - 88.5
    - 5.875
    layer:
    - 1
    - 0
    name: o5
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child:
    changed: {}
    child: null
    default:
      cross_section: strip
      gap_mmi: 0.25
      length_mmi: 5.5
      length_taper: 10.0
      straight:
        function: straight
      taper:
        function: taper
      width: null
      width_mmi: 2.5
      width_taper: 1.0
      with_bbox: true
    full:
      cross_section: strip
      gap_mmi: 0.25
      length_mmi: 5.5
      length_taper: 10.0
      straight:
        function: straight
      taper:
        function: taper
      width: null
      width_mmi: 2.5
      width_taper: 1.0
      with_bbox: true
    function_name: mmi1x2
    info: {}
    info_version: 2
    module: gdsfactory.components.mmi1x2
    name: mmi1x2
  default:
    bend:
      function: bend_s
    columns: 3
    splitter:
      function: mmi1x2
  full:
    bend:
      function: bend_s
    columns: 3
    splitter:
      function: mmi1x2
  function_name: splitter_chain
  info: {}
  info_version: 2
  module: gdsfactory.components.splitter_chain
  name: mmi1x2_splitter_chain
