name: mzi_arms
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 81.1
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    bend:
      function: bend_euler
    combiner: null
    delta_length: 10.0
    delta_yright: 0
    length_x: 0.1
    length_y: 0.8
    splitter:
      function: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  full:
    bend:
      function: bend_euler
    combiner: null
    delta_length: 10.0
    delta_yright: 0
    length_x: 0.1
    length_y: 0.8
    splitter:
      function: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  function_name: mzi_arms
  info: {}
  info_version: 2
  module: gdsfactory.components.mzi_arms
  name: mzi_arms
