name: coh_rx_dual_pol
ports:
  lo_o1:
    center:
    - -125.5
    - -300.0
    layer:
    - 1
    - 0
    name: lo_o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  pol1_i_out:
    center:
    - 350.0
    - 0.0
    layer:
    - 49
    - 0
    name: pol1_i_out
    orientation: 0.0
    port_type: placement
    shear_angle: null
    width: 2.0
  pol1_q_out:
    center:
    - 350.0
    - 15.0
    layer:
    - 45
    - 0
    name: pol1_q_out
    orientation: 0.0
    port_type: placement
    shear_angle: null
    width: 2.0
  pol2_i_out:
    center:
    - 350.0
    - -600.0
    layer:
    - 49
    - 0
    name: pol2_i_out
    orientation: 0.0
    port_type: placement
    shear_angle: null
    width: 2.0
  pol2_q_out:
    center:
    - 350.0
    - -615.0
    layer:
    - 45
    - 0
    name: pol2_q_out
    orientation: 0.0
    port_type: placement
    shear_angle: null
    width: 2.0
settings:
  changed: {}
  child: null
  default:
    bend:
      function: bend_euler
    cross_section: strip
    lo_input_coupler: null
    lo_splitter: mmi1x2
    signal_input_coupler: null
    signal_splitter: null
    single_pol_rx_spacing: 50.0
    splitter_coh_rx_spacing: 40.0
    spol_coh_rx:
      function: coh_rx_single_pol
  full:
    bend:
      function: bend_euler
    cross_section: strip
    lo_input_coupler: null
    lo_splitter: mmi1x2
    signal_input_coupler: null
    signal_splitter: null
    single_pol_rx_spacing: 50.0
    splitter_coh_rx_spacing: 40.0
    spol_coh_rx:
      function: coh_rx_single_pol
  function_name: coh_rx_dual_pol
  info: {}
  info_version: 2
  module: gdsfactory.components.coh_rx_dual_pol
  name: coh_rx_dual_pol
