name: straight_heater_metal_undercut_954d6e94_add_pads_bot_4867537a_add_pads_top_4867537a
ports:
  elec-pad_sizepad_size-straight_heater_metal_undercut_954d6e94-l_e1:
    center:
    - -16.0
    - 46.5
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-straight_heater_metal_undercut_954d6e94-l_e1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80
  l_e1:
    center:
    - -16.0
    - 0.0
    layer:
    - 49
    - 0
    name: l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e2:
    center:
    - -10.5
    - -5.5
    layer:
    - 49
    - 0
    name: l_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e3:
    center:
    - -5.0
    - 0.0
    layer:
    - 49
    - 0
    name: l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e4:
    center:
    - -10.5
    - 5.5
    layer:
    - 49
    - 0
    name: l_e4
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 100.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e1:
    center:
    - 105.0
    - 0.0
    layer:
    - 49
    - 0
    name: r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e2:
    center:
    - 110.5
    - -5.5
    layer:
    - 49
    - 0
    name: r_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e3:
    center:
    - 116.0
    - 0.0
    layer:
    - 49
    - 0
    name: r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e4:
    center:
    - 110.5
    - 5.5
    layer:
    - 49
    - 0
    name: r_e4
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  changed:
    component:
      component: straight_heater_metal_undercut
      settings:
        length: 100.0
        with_undercut: false
    port_names:
    - l_e1
  child:
    changed:
      component:
        component: straight_heater_metal_undercut
        settings:
          length: 100.0
          with_undercut: false
      port_names:
      - l_e1
    child:
      changed:
        length: 100.0
        with_undercut: false
      child: null
      default:
        cross_section_heater: heater_metal
        cross_section_heater_undercut: strip_heater_metal_undercut
        cross_section_waveguide_heater: strip_heater_metal
        heater_taper_length: 5.0
        heater_width: 2.5
        length: 320.0
        length_straight_input: 15.0
        length_undercut: 30.0
        length_undercut_spacing: 6.0
        ohms_per_square: null
        port_orientation1: null
        port_orientation2: null
        via_stack: via_stack_heater_mtop
        with_undercut: true
      full:
        cross_section_heater: heater_metal
        cross_section_heater_undercut: strip_heater_metal_undercut
        cross_section_waveguide_heater: strip_heater_metal
        heater_taper_length: 5.0
        heater_width: 2.5
        length: 100.0
        length_straight_input: 15.0
        length_undercut: 30.0
        length_undercut_spacing: 6.0
        ohms_per_square: null
        port_orientation1: null
        port_orientation2: null
        via_stack: via_stack_heater_mtop
        with_undercut: false
      function_name: straight_heater_metal_undercut
      info:
        resistance: null
      info_version: 2
      module: gdsfactory.components.straight_heater_metal
      name: straight_heater_metal_undercut_954d6e94
    default:
      bend: wire_corner
      component:
        function: straight_heater_metal_undercut
        settings:
          with_undercut: false
      component_name: null
      cross_section: metal_routing
      get_input_labels_function: null
      layer_label: TEXT
      optical_routing_type: 1
      pad:
        function: pad
        settings:
          size: pad_size
      pad_port_labels: null
      pad_port_name: e1
      pad_spacing: pad_spacing
      port_names: null
      select_ports:
        function: select_ports
        settings:
          port_type: electrical
      straight_separation: null
    full:
      bend: wire_corner
      component:
        component: straight_heater_metal_undercut
        settings:
          length: 100.0
          with_undercut: false
      component_name: null
      cross_section: metal_routing
      get_input_labels_function: null
      layer_label: TEXT
      optical_routing_type: 1
      pad:
        function: pad
        settings:
          size: pad_size
      pad_port_labels: null
      pad_port_name: e1
      pad_spacing: pad_spacing
      port_names:
      - l_e1
      select_ports:
        function: select_ports
        settings:
          port_type: electrical
      straight_separation: null
    function_name: add_pads_bot
    info:
      resistance: null
    info_version: 2
    module: gdsfactory.routing.add_pads
    name: straight_heater_metal_undercut_954d6e94_add_pads_bot_4867537a
  default:
    component:
      function: straight_heater_metal_undercut
      settings:
        with_undercut: false
  full:
    component:
      component: straight_heater_metal_undercut
      settings:
        length: 100.0
        with_undercut: false
    port_names:
    - l_e1
  function_name: add_pads_top
  info:
    resistance: null
  info_version: 2
  module: gdsfactory.routing.add_pads
  name: straight_heater_metal_undercut_954d6e94_add_pads_bot_4867537a_add_pads_top_4867537a
