name: grating_coupler_elliptical_trenches_20fa09db
ports:
  o1:
    center:
    - 10.5
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
  opt_tm_1530_15:
    center:
    - 32.68
    - 0.0
    layer:
    - 1
    - 0
    name: opt_tm_1530_15
    orientation: 0
    port_type: opt_tm_1530_15
    shear_angle: null
    width: 10
settings:
  changed:
    grating_line_width: 0.6
    neff: 1.8
    polarization: tm
  child: null
  default:
    cross_section: strip
    end_straight_length: 0.2
    fiber_angle: 15.0
    grating_line_width: 0.343
    layer_trench: SHALLOW_ETCH
    n_periods: 30
    ncladding: 1.443
    neff: 2.638
    p_start: 26
    polarization: te
    taper_angle: 30.0
    taper_length: 16.6
    trenches_extra_angle: 9.0
    wavelength: 1.53
  full:
    cross_section: strip
    end_straight_length: 0.2
    fiber_angle: 15.0
    grating_line_width: 0.6
    layer_trench: SHALLOW_ETCH
    n_periods: 30
    ncladding: 1.443
    neff: 1.8
    p_start: 26
    polarization: tm
    taper_angle: 30.0
    taper_length: 16.6
    trenches_extra_angle: 9.0
    wavelength: 1.53
  function_name: grating_coupler_elliptical_trenches
  info:
    period: 1.072
    polarization: tm
    wavelength: 1.53
  info_version: 2
  module: gdsfactory.components.grating_coupler_elliptical_trenches
  name: grating_coupler_elliptical_trenches_20fa09db
