name: optimal_step
ports:
  e1:
    center:
    - -38.132
    - 5.0
    layer:
    - 1
    - 0
    name: e1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 10
  e2:
    center:
    - 112.672
    - 11.0
    layer:
    - 1
    - 0
    name: e2
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 22
settings:
  changed: {}
  child: null
  default:
    anticrowding_factor: 1.2
    end_width: 22
    layer:
    - 1
    - 0
    num_pts: 50
    start_width: 10
    symmetric: false
    width_tol: 0.001
  full:
    anticrowding_factor: 1.2
    end_width: 22
    layer:
    - 1
    - 0
    num_pts: 50
    start_width: 10
    symmetric: false
    width_tol: 0.001
  function_name: optimal_step
  info:
    num_squares: 7.986
  info_version: 2
  module: gdsfactory.components.optimal_step
  name: optimal_step
