name: grating_coupler_elliptical_lumerical
ports:
  o1:
    center:
    - 0.24
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
  opt_te_1554_5:
    center:
    - 19.67
    - 0.0
    layer:
    - 1
    - 0
    name: opt_te_1554_5
    orientation: 0
    port_type: opt_te_1554_5
    shear_angle: null
    width: 10
settings:
  changed: {}
  child: null
  default:
    bias_gap: 0
    fiber_angle: 5
    info: null
    layer: WG
    layer_slab: SLAB150
    parameters:
    - -2.43
    - 0.1
    - 0.48
    - 0.1
    - 0.607
    - 0.1
    - 0.45
    - 0.1
    - 0.427
    - 0.1
    - 0.476
    - 0.1
    - 0.503
    - 0.1
    - 0.51
    - 0.1
    - 0.494
    - 0.108
    - 0.474
    - 0.15
    - 0.433
    - 0.184
    - 0.387
    - 0.236
    - 0.36
    - 0.243
    - 0.358
    - 0.261
    - 0.353
    - 0.247
    - 0.372
    - 0.229
    - 0.378
    - 0.225
    - 0.377
    - 0.22
    - 0.38
    - 0.219
    - 0.38
    - 0.217
    - 0.383
    - 0.218
    - 0.364
    - 0.237
    - 0.368
    - 0.249
    - 0.344
    - 0.273
    - 0.331
    - 0.274
    taper_angle: 55
    taper_length: 12.6
  full:
    bias_gap: 0
    fiber_angle: 5
    info: null
    layer: WG
    layer_slab: SLAB150
    parameters:
    - -2.43
    - 0.1
    - 0.48
    - 0.1
    - 0.607
    - 0.1
    - 0.45
    - 0.1
    - 0.427
    - 0.1
    - 0.476
    - 0.1
    - 0.503
    - 0.1
    - 0.51
    - 0.1
    - 0.494
    - 0.108
    - 0.474
    - 0.15
    - 0.433
    - 0.184
    - 0.387
    - 0.236
    - 0.36
    - 0.243
    - 0.358
    - 0.261
    - 0.353
    - 0.247
    - 0.372
    - 0.229
    - 0.378
    - 0.225
    - 0.377
    - 0.22
    - 0.38
    - 0.219
    - 0.38
    - 0.217
    - 0.383
    - 0.218
    - 0.364
    - 0.237
    - 0.368
    - 0.249
    - 0.344
    - 0.273
    - 0.331
    - 0.274
    taper_angle: 55
    taper_length: 12.6
  function_name: grating_coupler_elliptical_lumerical
  info:
    polarization: te
    wavelength: 1.554
    xinput: -2.43
  info_version: 2
  module: gdsfactory.components.grating_coupler_elliptical_lumerical
  name: grating_coupler_elliptical_lumerical
