name: bend_straight_bend
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 20.0
    - 30.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    angle: 90
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        info:
          type: strip
        name: strip
    direction: ccw
    npoints: 720
    p: 0.5
    straight_length: 10.0
    with_arc_floorplan: true
  full:
    angle: 90
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        info:
          type: strip
        name: strip
    direction: ccw
    npoints: 720
    p: 0.5
    straight_length: 10.0
    with_arc_floorplan: true
  function_name: bend_straight_bend
  info: {}
  info_version: 2
  module: gdsfactory.components.bend_euler
  name: bend_straight_bend
