name: bend_euler_angle180
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - 20.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    angle: 180
  child: null
  default:
    angle: 90.0
    cross_section: strip
    direction: ccw
    npoints: null
    p: 0.5
    with_arc_floorplan: true
    with_bbox: true
  full:
    angle: 180
    cross_section: strip
    direction: ccw
    npoints: null
    p: 0.5
    with_arc_floorplan: true
    with_bbox: true
  function_name: bend_euler
  info:
    dy: 0.0
    function_name: cross_section
    length: 42.817
    radius: 10.0
    radius_min: 9.086
    route_info:
      length: 42.817
      n_bend_90: 2.0
      strip_length: 42.817
      type: strip
      weight: 42.817
    settings:
      add_bbox: null
      add_pins:
        function: add_pins
        settings:
          function:
            function: add_pin_rectangle_inside
            settings:
              layer_label: null
              pin_length: 0.001
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers: null
      bbox_offsets: null
      cladding_layers: null
      cladding_offsets: null
      cladding_simplify: null
      decorator: null
      end_straight_length: 0.01
      gap: 3.0
      info:
        type: strip
      layer: WG
      min_length: 0.01
      mirror: false
      name: strip
      offset: 0
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      radius: 10.0
      sections: null
      snap_to_grid: null
      start_straight_length: 0.01
      taper_length: 10.0
      width: 0.5
      width_wide: null
    type: strip
    width: 0.5
  info_version: 2
  module: gdsfactory.components.bend_euler
  name: bend_euler_angle180
