name: ring_single_add_trenches_06939900
ports:
  o1:
    center:
    - -17.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      function: ring_single
  child:
    changed: {}
    child: null
    default:
      bend:
        function: bend_euler
      coupler_ring:
        function: coupler_ring
      cross_section: strip
      gap: 0.2
      length_x: 4.0
      length_y: 0.6
      radius: 10.0
    full:
      bend:
        function: bend_euler
      coupler_ring:
        function: coupler_ring
      cross_section: strip
      gap: 0.2
      length_x: 4.0
      length_y: 0.6
      radius: 10.0
    function_name: ring_single
    info: {}
    info_version: 2
    module: gdsfactory.components.ring_single
    name: ring_single
  default:
    bot: true
    component:
      function: coupler
    cross_section: rib_with_trenches
    left: false
    right: false
    top: true
  full:
    bot: true
    component:
      function: ring_single
    cross_section: rib_with_trenches
    left: false
    right: false
    top: true
  function_name: add_trenches
  info: {}
  info_version: 2
  module: gdsfactory.components.add_trenches
  name: ring_single_add_trenches_06939900
