name: taper_from_csv
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 35.23
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 3.0
settings:
  changed: {}
  child: null
  default:
    cross_section: strip
    filepath: taper_strip_0p5_3_36
  full:
    cross_section: strip
    filepath: taper_strip_0p5_3_36
  function_name: taper_from_csv
  info: {}
  info_version: 2
  module: gdsfactory.components.taper_from_csv
  name: taper_from_csv
